package model.enums;

import java.io.Serializable;

public enum TypeParam implements Serializable 
{
    VERSIONS, FILTREDATASTAGE, ABSOLUTEPATH, NOMFICHIER, NOMFICHIERDATASTAGE, ABSOLUTEPATHHISTO, 
    SQDIRECTION, SQDEPARTEMENT, SQSERVICE, SQRESPSERVICE, SQCLARITY, SQLIBELLE, SQCPI, SQEDITION, SQLOT, SQENV, SQANOMALIE, SQETAT, SQSECURITE, SQREMARQUE, SQTRAITE, SQVERSION, SQDATECREATION;
}
